package com.famstudio.tiktok.util

const val VIDEO_URL = "VIDEO_URL"
const val AUDIO_URL = "AUDIO_URL"
const val VIDEO_TITLE = "VIDEO_TITLE"
const val PROFILE_NAME = "PROFILE_NAME"
const val PROFILE_AVATAR = "PROFILE_AVATAR"
const val PROFILE_ID = "PROFILE_ID"
const val DURATION = "PRoOFILE_ID"
const val SIZE = "PROFILE_ID"
const val PERSON_NAME = "PERSON_NAME"
const val PERSON_GIVEN_NAME = "PERSON_GIVEN_NAME"
const val PERSON_EMAIL = "PERSON_EMAIL"
const val PERSON_ID = "PERSON_ID"
const val PHOTO_URL = "PHOTO_URL"